/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;
import AppPackage.AnimationClass;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
/**
 *
 * @author Roberto Castro
 */
public class Frame extends javax.swing.JFrame {
    
    AnimationClass ac = new AnimationClass();
    Thread myTread;
    ControlSubThread mt;
    ListAlbum lstAlbum;
    int sleepInterval = 2000;
    AdminAlbum admAlbum = null;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        setLocationRelativeTo(null);   
        lstAlbum = getListAlbum();
        fillAlbumSelect();
        
        if(!lstAlbum.Albumes.isEmpty()){
            mt = new ControlSubThread(sleepInterval,lstAlbum.Albumes.get(0),img1,start);
        }
        //mt.start();
    }
    
    public ListAlbum getListAlbum(){
        FileDataXML file = new FileDataXML();
        return file.loadFile();
    }
    
    public void fillAlbumSelect(){
        album.removeAllItems();
        
        
        PopupMenuListener listener = new PopupMenuListener() {
            boolean initialized = false;

            public void popupMenuCanceled(PopupMenuEvent e) {
            }

            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
            }

            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
                System.out.println("Hola");
                lstAlbum = getListAlbum();
                if (!initialized) {
                    String[] flavors = new String[lstAlbum.Albumes.size()];
                    for(int x=0;x<lstAlbum.Albumes.size();x++){
                        //album.addItem(alb.Nombre);
                        flavors[x] = lstAlbum.Albumes.get(x).Nombre;
                    }
                    //lstAlbum.Albumes.toArray(flavors);
                    //System.out.println(flavors);
                    JComboBox combo = (JComboBox) e.getSource();
                    ComboBoxModel model = new DefaultComboBoxModel(flavors);
                    combo.setModel(model);
                    //initialized = true;
                }
            }
          };
        
        album.addPopupMenuListener(listener);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        stop = new javax.swing.JButton();
        start = new javax.swing.JButton();
        loop = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();
        next = new javax.swing.JToggleButton();
        first = new javax.swing.JToggleButton();
        last = new javax.swing.JToggleButton();
        newalbum = new javax.swing.JButton();
        lblSelect = new javax.swing.JLabel();
        album = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Album de Fotografías");
        getContentPane().setLayout(new java.awt.CardLayout());

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        left.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        container.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Stop.png"))); // NOI18N
        stop.setBorder(null);
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });
        right.add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 50, 50));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Play.png"))); // NOI18N
        start.setBorder(null);
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        right.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 50));

        loop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Loop.png"))); // NOI18N
        loop.setBorder(null);
        loop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopActionPerformed(evt);
            }
        });
        right.add(loop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 50, 50));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Prev.png"))); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        right.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 50));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Next.png"))); // NOI18N
        next.setBorder(null);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        right.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 50, 50));

        first.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/First.png"))); // NOI18N
        first.setBorder(null);
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });
        right.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 50, 50));

        last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Last.png"))); // NOI18N
        last.setBorder(null);
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });
        right.add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 50, 50));

        newalbum.setText("Albumes");
        newalbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newalbumActionPerformed(evt);
            }
        });
        right.add(newalbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        lblSelect.setText("Seleccione album:");
        lblSelect.setToolTipText("");
        right.add(lblSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        album.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumActionPerformed(evt);
            }
        });
        right.add(album, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        container.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 200, 500));

        getContentPane().add(container, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void albumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumActionPerformed
        // TODO add your handling code here:        
        //fillAlbumSelect(lstAlbum);
        if(mt != null)
            mt.stop();
        for(Album alb: lstAlbum.Albumes){
            if(alb.Nombre == album.getSelectedItem()){
                mt = new ControlSubThread(sleepInterval,alb,img1,start);
            }
        }
    }//GEN-LAST:event_albumActionPerformed

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        mt.stop();
        start.setIcon(new ImageIcon(getClass().getResource("/img/Play.png")));
    }//GEN-LAST:event_stopMouseClicked

    private void startMouseClicked(java.awt.event.MouseEvent evt) {                                   
        if(mt.isRunning())
            mt.pause();
        else
            mt.start();
        
    }                                      

    private void loopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopActionPerformed
        System.out.println(loop.isSelected());
        if(loop.isSelected()){
            mt.loop(true);
            loop.setIcon(new ImageIcon(getClass().getResource("/img/LoopActive.png")));
        } else {
            mt.loop(false);
            loop.setIcon(new ImageIcon(getClass().getResource("/img/Loop.png")));
        }
    }//GEN-LAST:event_loopActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        mt.pause();
        mt.movePrev();
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        mt.pause();
        mt.moveNext();
    }//GEN-LAST:event_nextActionPerformed

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        mt.pause();
        mt.moveFirst();
    }//GEN-LAST:event_firstActionPerformed

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        mt.pause();
        mt.moveLast();
    }//GEN-LAST:event_lastActionPerformed

    private void newalbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newalbumActionPerformed
        if(admAlbum != null && admAlbum.formClosed == false){
            admAlbum = null;
        }
        if(admAlbum == null){
            admAlbum = new AdminAlbum();            
        }
        admAlbum.setDatos(lstAlbum);
        admAlbum.setVisible(true);
    }//GEN-LAST:event_newalbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> album;
    private javax.swing.JToggleButton back;
    private javax.swing.JPanel container;
    private javax.swing.JToggleButton first;
    private javax.swing.JLabel img1;
    private javax.swing.JToggleButton last;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JPanel left;
    private javax.swing.JToggleButton loop;
    private javax.swing.JButton newalbum;
    private javax.swing.JToggleButton next;
    private javax.swing.JPanel right;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
